### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [MarselScheer/simTool#1]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _simTool_ package imports or suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. The errors seem to relate to expectations for column names in `as_tibble.matrix()` which are no longer true for the _tibble_ release candidate.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding of the problem?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by MarselScheer** [comment]
Issue was already solved in 243e24c069dce2156228538cbcd344e40c5c9c4e.

PS: Sorry for answering thus late! Somehow this repo was not on my watchlist?!?
